stages:
  - install
  - lint
  - test
  - cleanup

install:
  stage: install
  cache:
    key: $CI_BUILD_REF_NAME
    paths:
      - node_modules/
  script:
    - npm install
  tags:
    - nodejs-8

lint:
  stage: lint
  cache:
    key: $CI_BUILD_REF_NAME
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run lint
  tags:
    - nodejs-8

test:
  stage: test
  cache:
    key: $CI_BUILD_REF_NAME
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run test:ci
  tags:
    - nodejs-8

cleanup:
  stage: cleanup
  when: always
  except:
    - master
  script:
    - clear-cache -g "$CI_PROJECT_NAMESPACE" -p "$CI_PROJECT_NAME" -b "$CI_BUILD_REF_NAME"
  tags:
    - nodejs-8
